version: "3.3"

services:
  ember:
    container_name: ember
    image: ember
    build: ./docker
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - cache
      - database
    volumes:
      - "./volumes/html/:/var/www/html/"
      - "./volumes/assets/:/var/www/assets/"
    env_file: .env

  database:
    container_name: ember-database
    image: mysql:5
    restart: always
    env_file: .env
    volumes:
      - "./volumes/database:/var/lib/mysql"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"

  cache:
    container_name: ember-cache
    image: redis:alpine
    restart: always
    volumes:
        - "./volumes/cache:/data"
